/**
 * Contains the name of all screens in application
 **/

export const NAVIGATION_SCREENS = {
    Registeration: {
        Login: "Login",
    },
    User: {
        Home: 'Home',
        OrgDetail: 'OrgDetail',
        ProductDetail: 'ProductDetail',
        Settings: 'Settings',
        Consents: 'Consents',
        CheckoutSreen: 'CheckoutSreen',
        PaymentListing: 'PaymentListing',
        PaymentDetail: 'PaymentDetail',
        ProfileScreen: 'ProfileScreen',
        ActiveMembershipListing: 'ActiveMembershipListing',
        MemberShipDetail: 'MemberShipDetail',
        ExpiredMembershipListing: 'ExpiredMembershipListing',
        MessageListingScreen: 'MessageListingScreen',
        ArchiveMessageListingScreen: 'ArchiveMessageListingScreen',
        MessageDetailScreen: 'MessageDetailScreen',
        ShareLinkScreen: 'ShareLinkScreen',
        TwoFAPhoneScreen: 'TwoFAPhoneScreen',
        MembershipCardFullScreen: 'MembershipCardFullScreen',
        DeleteAccountScreen: 'DeleteAccountScreen',
        SwitchAccountScreen: 'SwitchAccountScreen',
        MobilePayStatus: 'MobilePayStatus',
        UserFeedback: 'UserFeedback',
        MobilePaySubscriptionStatus: 'MobilePaySubscriptionStatus',
        ChangePhoneNumber:'ChangePhoneNumber',
        DeveloperScreen:'DeveloperScreen',
        OrganizationBoardMembers: 'OrganizationBoardMembers',
        NewsAndEventsListing: 'NewsAndEventsListing',
        OrganizationEventDetail: 'OrganizationEventDetail',
        OrganizationNewsDetail: 'OrganizationNewsDetail',
    },
    Admin: {
        OrganizationInfo: 'OrganizationInfo',
        AdminMemberListing: 'AdminMemberListing',
        AdminMemberDetail: 'AdminMemberDetail',
        AdminEditMemberScreen: 'AdminEditMemberScreen',
        AdminCreateAndInviteMemeber :'AdminCreateAndInviteMemeber',
        AdminCreatePayment : 'AdminCreatePayment',
        AdminMessageListingScreen: 'AdminMessageListingScreen',
        AdminMessageDetailScreen: 'AdminMessageDetailScreen',
        AdminCreateMessage : 'AdminCreateMessage',
        AdminAffiliatedOrganizationStats: 'AdminAffiliatedOrganizationStats',
        AdminCreateBoardMember: 'AdminCreateBoardMember',
        AdminManageOrganizationBoardMembers: 'AdminManageOrganizationBoardMembers',
        AdminNewsAndEventsListing: 'AdminNewsAndEventsListing',
        AdminOrganizationEventDetail: 'AdminOrganizationEventDetail',
        AdminOrganizationNewsDetail: 'AdminOrganizationNewsDetail',
        AdminNewsDetail: 'AdminNewsDetail',
        AdminEventDetail: 'AdminEventDetail',
        AdminCreateOrganizationNews: 'AdminCreateOrganizationNews',
        AdminCreateOrganizationEvent: 'AdminCreateOrganizationEvent',
    }
}